title: Olimpo II
description: Departamentos
show_downloads: false
google_analytics:
theme: jekyll-theme-dinky

departments:
  - name: Diseño
    subjects:
      - name: Mercadotécnia
        pages:
          - title: Descripción de Marca
            url: /disn/mercadotecnia/descripcion_marca
          - title: Objetivos
            url: /disn/mercadotecnia/objetivos
          - title: Público Objetivo y DAFO
            url: /disn/mercadotecnia/publ_obj_dafo

      - name: Supuesto 2
        pages:
          - title: Supuesto 2
            url: /disn/supuesto_2/supuesto_2
