title: Olimpo II
description: Transversales
show_downloads: false
google_analytics:
theme: jekyll-theme-dinky

departments:
  - name: Diseño
    url: /disn
  - name: Jardinería
    url: /jardineria
  - name: Dinamización
    url: /dinamizacion
  - name: Turismo
    url: /turismo
